language: go

branches:
  only:
    master

notifications:
  email: false

jobs: 
  include:
  - stage: "Build"
    name: "Docker Image"
    script: 
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t helloworld .
    - docker images
    - docker tag helloworld $DOCKER_USERNAME/test:helloworld
    - docker push $DOCKER_USERNAME/test:helloworld
  - stage: "Test"
    name: "Pull and test image"
    before_install: 
      - sudo apt-get install jq
    script: 
    - TOKEN=$( curl -sSLd "username=${DOCKER_USERNAME}&password=${DOCKER_PASSWORD}" https://hub.docker.com/v2/users/login | jq -r ".token" )
    - curl -sH "Authorization: JWT $TOKEN" "https://hub.docker.com/v2/repositories/${DOCKER_USERNAME}/test:helloworld" | jq .
  - stage: "Deploy"