language: go

branches:
  only:
    master

notifications:
  email: false

jobs: 
  include:
  - stage: "Build"
    name: "Docker Image"
    script: 
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t helloworld .
    - docker images
    - docker tag helloworld $DOCKER_USERNAME/test:helloworld
    - docker push $DOCKER_USERNAME/test:helloworld
  - stage: "Test"
    name: "Unit test"
  - stage: "Deploy"